src/menus/urls.py
from django.conf.urls import url


from .views import (
	ItemCreateView,
    ItemDetailView,
    ItemListView,
    ItemUpdateView,
)

urlpatterns = [
    url(r'^create/$', ItemCreateView.as_view(), name='create'),
    # url(r'^(?P<pk>\d+)/edit/$', ItemUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/$', ItemUpdateView.as_view(), name='detail'),
    url(r'^$', ItemListView.as_view(), name='list'),
]

src/muypicky/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

from django.contrib.auth.views import LoginView

from profiles.views import ProfileFollowToggle

from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^profile-follow/$', ProfileFollowToggle.as_view(), name='follow'),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^u/', include('profiles.urls', namespace='profiles')),
    url(r'^items/', include('menus.urls', namespace='menus')),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    url(r'^contact/$', TemplateView.as_view(template_name='contact.html'), name='contact'),
]

src/restaurants/urls.py
from django.conf.urls import url


from restaurants.views import (
    RestaurantListView,
    RestaurantDetailView,
    RestaurantCreateView,
    RestaurantUpdateView
)

urlpatterns = [
    url(r'^create/$', RestaurantCreateView.as_view(), name='create'),
	# url(r'^(?P<slug>[\w-]+)/edit/$', RestaurantUpdateView.as_view(), name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', RestaurantUpdateView.as_view(), name='detail'),
    url(r'^$', RestaurantListView.as_view(), name='list'),
]

src/restaurants/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.db.models.signals import pre_save, post_save
from django.core.urlresolvers import reverse

from .utils import unique_slug_generator
from .validators import validate_category


User = settings.AUTH_USER_MODEL

class RestaurantLocationQuerySet(models.query.QuerySet):
	def search(self, query):
		if query:
			query = query.strip()
			return self.filter(
				Q(name__icontains=query)|
				Q(location__icontains=query)|
				Q(location__iexact=query)|
				Q(category__icontains=query)|
				Q(category__iexact=query)|
				Q(item__name__icontains=query)|
				Q(item__contents__icontains=query)
			).distinct()
		
		return self

class RestaurantLocationManager(models.Manager):
	def get_queryset(self):
		return RestaurantLocationQuerySet(self.model, using=self._db)
	def search(self, query):
		return self.get_queryset().search(query)
class RestaurantLocation(models.Model):
	owner 		= models.ForeignKey(User)
	name		= models.CharField(max_length=120)
	location	= models.CharField(max_length=120, null=True, blank=True)
	category	= models.CharField(max_length=120, null=True, blank=True, validators=[validate_category])
	timestamp	= models.DateTimeField(auto_now_add=True)
	updated 	= models.DateTimeField(auto_now=True)
	slug		= models.SlugField(null=True, blank=True)

	objects = RestaurantLocationManager()

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse('restaurants:detail', kwargs={'slug':self.slug})
		# f"/restaurants/{self.slug}"

	@property
	def title(self):
		return self.name


def rl_pre_save_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.category = instance.category.capitalize()
		instance.slug = unique_slug_generator(instance)
	

# def rl_post_save_receiver(sender, instance, created, *args, **kwargs):
# 	print('saved')
# 	print(instance.timestamp)
# 	if not instance.slug:
# 		instance.slug = unique_slug_generator(instance)
# 		instance.save()


pre_save.connect(rl_pre_save_receiver, sender=RestaurantLocation)

# post_save.connect(rl_post_save_receiver, sender=RestaurantLocation)

src/restaurants/forms.py
from django import forms

from .models import RestaurantLocation
from .validators import validate_category

class RestaurantCreateForm(forms.Form):
	name		= forms.CharField()
	location	= forms.CharField(required=False)
	category	= forms.CharField(required=False)

	def clean_name(self):
		name = self.cleaned_data.get("name")
		if name == "Hello":
			raise forms.ValidationError("Not a valid name")
		return name


class RestaurantLocationCreateForm(forms.ModelForm):
	# email = forms.EmailField()
	# category = forms.CharField(required=False, validators=[validate_category])
	class Meta:
		model = RestaurantLocation
		fields = [
			'name',
			'location',
			'category',
		]

	def clean_name(self):
		name = self.cleaned_data.get("name")
		if name == "Hello":
			raise forms.ValidationError("Not a valid name")
		return name

	# def clean_email(self):
	# 	email = self.cleaned_data.get("email")
	# 	if ".edu" in email:
	# 		raise forms.ValidationError("We do not accept edu emails")
	# 	return email

src/restaurants/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView

from .forms import RestaurantCreateForm, RestaurantLocationCreateForm
from .models import RestaurantLocation


class RestaurantListView(LoginRequiredMixin, ListView):
	def get_queryset(self):
		return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantDetailView(DetailView):
	def get_queryset(self):
		return RestaurantLocation.objects.filter(owner=self.request.user)


class RestaurantCreateView(LoginRequiredMixin, CreateView):
	form_class = RestaurantLocationCreateForm
	login_url='/login/'
	template_name = 'form.html'
	# success_url = '/restaurants/'

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.owner = self.request.user
		return super(RestaurantCreateView, self).form_valid(form)

	def get_context_data(self, *args, **kwargs):
		context = super(RestaurantCreateView, self).get_context_data(*args, **kwargs)
		context['title'] = 'Add Restaurant'
		return context


class RestaurantUpdateView(LoginRequiredMixin, UpdateView):
	form_class = RestaurantLocationCreateForm
	login_url='/login/'
	template_name = 'restaurants/detail-update.html'
	# success_url = '/restaurants/'

	def get_context_data(self, *args, **kwargs):
		context = super(RestaurantUpdateView, self).get_context_data(*args, **kwargs)
		name = self.get_object().name
		context['title'] = f'Update Restaurant: {name}'
		return context

	def get_queryset(self):
		return RestaurantLocation.objects.filter(owner=self.request.user)

src/restaurants/templates/restaurants/detail-update.html
{% extends "base.html" %}

{% block head_title %}{{ form.instance.title }} | Restaurants || {{ block.super}}{% endblock head_title %}

{% block content %}
<h1>{{ form.instance.title }} <small> {{ form.instance.category }}</small></h1>
<p>{{ form.instance.location }}</p>
<p>{{ form.instance.timestamp }}, {{ form.instance.updated|timesince }} ago</p>

<hr/>
<h3>Make Changes</h3>
{% include 'snippets/form-snippet.html' with form=form %}

{% endblock %}

src/restaurants/templates/restaurants/restaurantlocation_detail.html
{% extends "base.html" %}

{% block head_title %}Restaurants || {{ block.super}}{% endblock head_title %}

{% block content %}
<h1>{{ object.title }} <small> {{ object.category }}</small></h1>
<p>{{ object.location }}</p>
<p>{{ object.timestamp }}, {{ object.updated|timesince }} ago</p>

{% endblock %}

src/restaurants/templates/restaurants/restaurantlocation_list.html
{% extends "base.html" %}

{% block head_title %}Restaurants || {{ block.super}}{% endblock head_title %}

{% block content %}
<h1>My Restaurants <small><a href='{% url "restaurants:create"%}'>Add</a></small></h1>

<ul>
{% for obj in object_list %}
	<li><a href='{{ obj.get_absolute_url }}'>{{ obj }}</a><br/>
	{{ obj.name }} {{ obj.location }} {{ obj.category }} {{ obj.timestamp }} {{ obj.updated }}</li>
{% empty %}
	<li><a href='{% url "restaurants:create"%}'>Add One</a></li>
{% endfor %}
</ul>

{% endblock %}

src/restaurants/templates/restaurants/restaurants_list.html
{% extends "base.html" %}

{% block head_title %}Restaurants || {{ block.super}}{% endblock head_title %}

{% block content %}
<h1>Restaurant List</h1>

<ul>
{% for obj in object_list %}
	<li>{{ obj.name }} {{ obj.location }} {{ obj.category }} {{ obj.timestamp }} {{ obj.updated }}</li>
{% endfor %}
</ul>

{% endblock %}